### ISSUE TITLE
Trying to access beyond buffer length

### ISSUE THREAD

**Issue by imkrish7** [Segun-Ogundipe/solana-mail-web#3]
inboxActions.ts:42 RangeError: Trying to access beyond buffer length
    at checkOffset (bundle.js:53001:36)
    at Uint8Array.readUInt32LE (bundle.js:53057:18)
    at BinaryReader.readU32 (bundle.js:51434:28)
    at BinaryReader.propertyDescriptor.value (bundle.js:51400:29)
    at BinaryReader.readArray (bundle.js:51486:22)
    at BinaryReader.propertyDescriptor.value (bundle.js:51400:29)
    at deserializeField (bundle.js:51651:23)
    at deserializeStruct (bundle.js:51703:27)
    at deserialize (bundle.js:51730:18)
    at Function.decode

**Comment by Segun-Ogundipe** [comment]
This is possibly an issue where struct deserialization function is
supplied with the wrong integer length

**Comment by imkrish7** [comment]
Where in contract

**Comment by Segun-Ogundipe** [comment]
It's a JavaScript error. Probably in one of the borsh models

**Comment by Segun-Ogundipe** [comment]
Hi @imkrish7, were you able to fix this?

**Comment by imkrish7** [comment]
yes. The issue was, Response of the account info was wrong. Thanks for the help.

**Comment by Segun-Ogundipe** [comment]
Glad to hear it!
